// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsehzmqywlpzceyctwrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzZWh6bXF5d2xwemNleWN0d3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1MzY2NzgsImV4cCI6MjA5MjExMjY3OH0.CT9NFT0eGz-zd4S5C77IKuNMvHySAN1oFBsIywO3-Hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});